<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyContainer</name>
   <tag></tag>
   <elementGuidId>1cf6491e-e40f-413f-bf64-54aff8dd029d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearfix</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content_container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>birthdayItOk Wararakamot and 7 othersWord BlitzContinue PlayingJudy Ann Sunga🤔💭 Judy has started a game with you. It's your turn!HxBibleStudyCome kill walkers and save the world!Instant Games1111Listings You Recently ViewedContact Seller₱1,500₱1,000₱1,400See MoreSponsoredCreate AdStart your online business today!pages.lazada.com.phKeep up with the trend when you sell on Lazada.Sign up as a seller for FREE and enjoy hass...Words From The WiseHBR.ORGWhy We Procrastinate When We Have Long Deadlines is one of HBR's featured articles. Gain i...English (US) · Filipino · Bisaya · Español · Português (Brasil)Privacy · Terms · Advertising · Ad Choices · Cookies · More Facebook © 2020   Create PostPhoto/VideoTag FriendsCheck inPhoto/VideoTag FriendsCheck inFeeling/ActivityLive VideoGIFWatch PartyAsk for RecommendationsPlay with FriendsNews Feedcheckmarkcaution-solidOnly meYour StoryFriendsPostStoriesSee AllAdd to StoryGhenica MarieFatima Janine Cubacub SaplalaKelvin RambacudSee All StoriesNews Feed‎Junbert Oarde Sotto‎ to [PC] The Division 2 PhilippinesJust now · Skip back1:21Additional Visual SettingsEnter Watch And ScrollClick to enlargeCreate a clip from the last 60 secondsUnmuteClick to expandRibbon_Stool_GAminG_TVtriangle-downtriangle-upshareShareLive Video InterruptedThe broadcast has been paused. It should resume shortly.Live Video Not Available.It may contain content that is limited in the country you are in.This live video has ended.It'll be available to watch on Ribbon_Stool_GAminG_TV's timeline shortly.It looks like you may be having problems playing this video. If so, please try restarting your browser.ClosePosted by Ribbon_Stool_GAminG_TVFollowUnfollowLIVE1Ribbon_Stool_GAminG_TV is live now — playing Tom Clancy's The Division 2.FollowSee FirstFollowing3 mins · update Complete!!! tD timeLikeCommentShareCommentsWrite a comment...Borgy Hababag, Yuri Navarro and 48 friends like Uniqlo Philippines.Uniqlo PhilippinesSponsored · Join our UNIQLO Manager Candidate program and experience the role of an innovator, talent developer, problem solver, and business leader. Click the link below to sign up: https://s.uniqlo.com/2VoEVUs1.4K1.4K513 Comments179 SharesCj MacLikeCommentShare‎Oyo Boy Lasam‎ to Hachi's Buy and Sell GroupJust now · Additional Visual SettingsEnter Watch And ScrollClick to enlargeCreate a clip from the last 60 secondsUnmuteClick to expandSempiternaltriangle-downtriangle-upshareShareLive Video InterruptedThe broadcast has been paused. It should resume shortly.Live Video Not Available.It may contain content that is limited in the country you are in.This live video has ended.It'll be available to watch on Sempiternal's timeline shortly.It looks like you may be having problems playing this video. If so, please try restarting your browser.Closegta na boy badboyPosted by SempiternalFollowUnfollowLIVE353Sempiternal is live now — playing Grand Theft Auto V.FollowSee FirstFollowing2 hrs · gta ma men AORUS para sa matinding rtx2080SUPER natin Dyse One Philippines para sa malulupit ntng damit available at all leading department stores natiowide!!LikeCommentShareCommentsWrite a comment...Frederick Martin A. Ilagan is at Forward Motion Performance.12 mins · San Pablo City · Spent the whole day working on the wind master. Such a very beautiful bike. I like how the wheels and bars matches the finish of the frame . Thank you very much Boss @tjfabieiii for trusting me to work on your beautiful Elemento Wind Master. Please keep me updated on your fit.  #forwardmotionperformance  #fitted2perform+344LikeCommentShareCommentsWrite a comment...Chuck Pallingayan25 mins · Ops. 😂😂😂Pj Romero5 hrsGanda kotse Ganda damit Ganda  sapatos Dami pera ahh... Salamat mommy and daddy Un magulang mo halos hindi na matulog kaka trabaho Ikaw naman halos hindi ka na din matulog kaka tambay #penge achara #bangkarote See More4Darwin Yabut San Mateo, Trisha Miranda Carlos and 2 othersLikeCommentShareCommentsWrite a comment...‎Alex Tiquia‎ to PC Desktop/Laptops BUY/SELL and TRADE -PhilippinesJust now · Skip backAdditional Visual SettingsEnter Watch And ScrollClick to enlargeUnmuteClick to expandIFLEX WARE PCtriangle-downtriangle-upshareShareLive Video InterruptedThe broadcast has been paused. It should resume shortly.Live Video Not Available.It may contain content that is limited in the country you are in.This live video has ended.It'll be available to watch on IFLEX WARE PC's timeline shortly.It looks like you may be having problems playing this video. If so, please try restarting your browser.CloseALL IN ONE COMPUTERPosted by IFLEX WARE PCFollowUnfollowLIVE3IFLEX WARE PC is live now.FollowSee FirstFollowing5 mins · iFLEX WARE PC NOW LIVELikeCommentShareCommentsWrite a comment...‎Peter O'Shea‎ to The Division 2 PC Community1 hr · Loving the update. My Ace's build kills it now. Though Nemesis is now Nerf to s**t (700+ to 300+). I found this named marksman rifle, the DARKNESS and also managed to get 600+ armour and around 500+ health. (Will post pic when servers back online). But very happy with it all. So many build ideas.6618 CommentsLikeCommentCommentsView 4 more commentsAL Doble Everything changed. I like it tho... it works well to balance the game. I have 1.1mil armor and 300k health. Im running wicked and perfect vanguard. My savage wolverine hits for 70k base, then goes up once wicked is procked. My crusader shield has over 5mil in hp and a very fast regen speed. The new gear sets really help with tanky build. I also have plenty of haz protection.1Hide or report this · Like · Reply · 1hPeter O'Shea replied  ·  1 Reply   57 minsWrite a comment...More Posts</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_container&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content_container']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentCol']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
